version: "3.9"
services:
  db:
    container_name: pgdb
    image: postgres:12.0
    environment:
      PG_DATA: /data/postgres
    env_file:
      - development.env
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    restart: unless-stopped
  app:
    container_name: app
    image: money_transfer_app:latest
    links:
      - db
    env_file:
      - development.env
    ports:
      - "8080:8080"
  installer:
    container_name: app_install
    image: money_transfer_app_install:latest
    links:
      - db
    env_file:
      - development.env
volumes:
  db: