version: "3.9"
services:
  db:
    container_name: pgdb
    image: postgres:12.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    restart: unless-stopped
  app:
    container_name: app
    image: money_transfer_app:latest
    links:
      - db
    environment:
      DB_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db/postgres"
    ports:
      - "8080:8080"
volumes:
  db: